% Takes a transmitted signal, SNR, and doppler channel components and
% performs transmission through the Watterson channel. Returns transmittd
% dignal and H (channel coefficient matrix). Adds AWGN. 
%
% PARAMETERS
%   - Tx = transmitted signal
%   - SNR = SNR
%   - chanComp1, chanComp2 = doppler channel components generated by Watterson_channel.m
%   - gGauss1, gGauss2 = power gain of each doppler component

% default function call: Watterson_transmit(Tx, SNR, chanComp1, chanComp2, 1.2, 0.25)
function [Rx, H] = Watterson_transmit(Tx, SNR, chanComp1, chanComp2, gGauss1, gGauss2)
    [y1, g1] = chanComp1(Tx); % Watterson Comp1
    [y2, g2] = chanComp2(Tx); % Watterson Comp2
    Rx = sqrt(gGauss1) * y1 + sqrt(gGauss2) * y2; % Watterson Signal
    Rx = awgn(Rx,SNR); % Additive White Gaussian Noise
    H = sqrt(gGauss1) * g1 + sqrt(gGauss2) * g2; % Perfect Channel Estimation
end